In [1]:
%load_ext autoreload
%autoreload 2
import sys
sys.path.append("..")
from optimus import Optimus

# Create optimus
op = Optimus(master="local", app_name= "optimus", verbose = True)

In [2]:
# Put your db credentials here
db =  op.JDBC(
    db_type="xxxx",
    url="xxxx", 
    database= "xxxx", 
    user= "xxxx", 
    password = "xxxx", 
    port="xxxx")

In [3]:
db.tables()

In [4]:
df = db.table_to_df("places_interest", limit=None)

In [5]:
df.table()